#!/bin/bash

cnt=0

while [ $cnt -lt 10 ]
do
	filename="flow-one${cnt}"
	res="$(./generator --flow-one > ./flow-one/$filename)"
	cnt=$((cnt+1))
done

files=./flow-one/*

av_time=0
for file in $files
do
	#mkdir -p ./flow-one/results
	start="$(date +%s)"
	echo "$start"
	output="$(./lem-in < "$file" > /dev/null 2>&1 | wc -l)"
	echo "bbb"
	end="$(date +%s)"
	av_time=$(($end-$start+$av_time))
done

echo "average time is $(( av_time / 10 ))"
